# Generated by Django 2.1.3 on 2019-01-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='areas.Area', verbose_name='parent_area')),
            ],
            options={
                'verbose_name_plural': 'Administrative division',
                'verbose_name': 'Administrative division',
                'db_table': 'tb_areas',
            },
        ),
    ]
